services:
  - type: web
    name: nga-jetclean
    env: static
    buildCommand: echo "Static site, no build needed"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 